# Generated by Django 6.0.4 on 2026-04-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Medical Manager', 'Medical Manager'), ('Admin', 'Admin')], default='Receptionist', max_length=20),
        ),
    ]
